[package]
name = "stella"
description = "Rust-based, speedy Lua type checker"
authors = ["Yazalde Filimone <yazaldefilimon@gmail.com>"]
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
code_highlighter = "0.1.1"
serde = { version = "1.0.204", features = ["derive"] }

[dev-dependencies]
glob = "0.3.1"
insta = { version = "1.39.0", features = ["ron"] }

[profile.release]
opt-level = "z"   # Otimizar para o menor tamanho possível, use "3" para agressividade máxima
debug = false     # Não incluir informações de depuração
lto = "fat"       # Link Time Optimization, "fat" aplica otimizações mais agressivas
panic = "abort"   # Abortar no caso de pânico, em vez de desempilhar
codegen-units = 1 # Reduzir o número de unidades de geração de código para melhorar a otimização
