[package]
name = "stella"
description = "Rust-based, speedy Lua type checker"
authors = ["Yazalde Filimone <yazaldefilimon@gmail.com>"]
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
highlight_error = "0.1.1"
serde = { version = "1.0.204", features = ["derive"] }

[dev-dependencies]
glob = "0.3.1"
insta = { version = "1.39.0", features = ["ron"] }
